<?xml version="1.0" encoding="utf-8"?><Database Name="AdventureWorksLT2008_Data" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\AdventureWorksLT2008_Data.mdf;Integrated Security=True;Connect Timeout=30;User Instance=True" SettingsObjectName="CDH.LinqDBSchema.Properties.Settings" SettingsPropertyName="AdventureWorksLT2008_DataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="INFORMATION_SCHEMA.COLUMNS" Member="COLUMNs">
    <Type Name="COLUMN">
      <Column Name="TABLE_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="COLUMN_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="ORDINAL_POSITION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COLUMN_DEFAULT" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="IS_NULLABLE" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="DATA_TYPE" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CHARACTER_MAXIMUM_LENGTH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CHARACTER_OCTET_LENGTH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NUMERIC_PRECISION" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="NUMERIC_PRECISION_RADIX" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="NUMERIC_SCALE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATETIME_PRECISION" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CHARACTER_SET_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CHARACTER_SET_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CHARACTER_SET_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="COLLATION_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="COLLATION_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="COLLATION_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DOMAIN_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DOMAIN_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DOMAIN_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="INFORMATION_SCHEMA.PARAMETERS" Member="PARAMETERs">
    <Type Name="PARAMETER">
      <Column Name="SPECIFIC_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="SPECIFIC_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="SPECIFIC_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ORDINAL_POSITION" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PARAMETER_MODE" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="IS_RESULT" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="AS_LOCATOR" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="PARAMETER_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DATA_TYPE" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="CHARACTER_MAXIMUM_LENGTH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CHARACTER_OCTET_LENGTH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COLLATION_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="COLLATION_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="COLLATION_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CHARACTER_SET_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CHARACTER_SET_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CHARACTER_SET_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="NUMERIC_PRECISION" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="NUMERIC_PRECISION_RADIX" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="NUMERIC_SCALE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATETIME_PRECISION" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="INTERVAL_TYPE" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="INTERVAL_PRECISION" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="USER_DEFINED_TYPE_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="USER_DEFINED_TYPE_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="USER_DEFINED_TYPE_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="SCOPE_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="SCOPE_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="SCOPE_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="INFORMATION_SCHEMA.ROUTINES" Member="ROUTINEs">
    <Type Name="ROUTINE">
      <Column Name="SPECIFIC_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="SPECIFIC_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="SPECIFIC_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ROUTINE_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="ROUTINE_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="ROUTINE_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ROUTINE_TYPE" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MODULE_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MODULE_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MODULE_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="UDT_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="UDT_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="UDT_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DATA_TYPE" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CHARACTER_MAXIMUM_LENGTH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CHARACTER_OCTET_LENGTH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COLLATION_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="COLLATION_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="COLLATION_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CHARACTER_SET_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CHARACTER_SET_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CHARACTER_SET_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="NUMERIC_PRECISION" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="NUMERIC_PRECISION_RADIX" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="NUMERIC_SCALE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATETIME_PRECISION" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="INTERVAL_TYPE" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="INTERVAL_PRECISION" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TYPE_UDT_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TYPE_UDT_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TYPE_UDT_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="SCOPE_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="SCOPE_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="SCOPE_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MAXIMUM_CARDINALITY" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DTD_IDENTIFIER" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="ROUTINE_BODY" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ROUTINE_DEFINITION" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="EXTERNAL_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="EXTERNAL_LANGUAGE" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="PARAMETER_STYLE" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IS_DETERMINISTIC" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SQL_DATA_ACCESS" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IS_NULL_CALL" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SQL_PATH" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="SCHEMA_LEVEL_ROUTINE" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MAX_DYNAMIC_RESULT_SETS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="IS_USER_DEFINED_CAST" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="IS_IMPLICITLY_INVOCABLE" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CREATED" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LAST_ALTERED" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="INFORMATION_SCHEMA.SCHEMATA" Member="SCHEMATAs">
    <Type Name="SCHEMATA">
      <Column Name="CATALOG_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="SCHEMA_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="SCHEMA_OWNER" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DEFAULT_CHARACTER_SET_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DEFAULT_CHARACTER_SET_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DEFAULT_CHARACTER_SET_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="INFORMATION_SCHEMA.ROUTINE_COLUMNS" Member="ROUTINE_COLUMNs">
    <Type Name="ROUTINE_COLUMN">
      <Column Name="TABLE_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="COLUMN_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="ORDINAL_POSITION" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COLUMN_DEFAULT" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="IS_NULLABLE" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="DATA_TYPE" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CHARACTER_MAXIMUM_LENGTH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CHARACTER_OCTET_LENGTH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NUMERIC_PRECISION" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="NUMERIC_PRECISION_RADIX" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="NUMERIC_SCALE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATETIME_PRECISION" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CHARACTER_SET_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CHARACTER_SET_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CHARACTER_SET_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="COLLATION_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="COLLATION_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="COLLATION_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DOMAIN_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DOMAIN_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DOMAIN_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="INFORMATION_SCHEMA.TABLE_CONSTRAINTS" Member="TABLE_CONSTRAINTs">
    <Type Name="TABLE_CONSTRAINT">
      <Column Name="CONSTRAINT_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CONSTRAINT_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CONSTRAINT_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="TABLE_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CONSTRAINT_TYPE" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="IS_DEFERRABLE" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="INITIALLY_DEFERRED" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="INFORMATION_SCHEMA.TABLE_PRIVILEGES" Member="TABLE_PRIVILEGEs">
    <Type Name="TABLE_PRIVILEGE">
      <Column Name="GRANTOR" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="GRANTEE" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PRIVILEGE_TYPE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="IS_GRANTABLE" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="INFORMATION_SCHEMA.TABLES" Member="TABLEs">
    <Type Name="TABLE">
      <Column Name="TABLE_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="TABLE_TYPE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="INFORMATION_SCHEMA.VIEW_COLUMN_USAGE" Member="VIEW_COLUMN_USAGEs">
    <Type Name="VIEW_COLUMN_USAGE">
      <Column Name="VIEW_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="VIEW_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="VIEW_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="TABLE_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="COLUMN_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="INFORMATION_SCHEMA.VIEW_TABLE_USAGE" Member="VIEW_TABLE_USAGEs">
    <Type Name="VIEW_TABLE_USAGE">
      <Column Name="VIEW_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="VIEW_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="VIEW_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="TABLE_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="INFORMATION_SCHEMA.VIEWS" Member="VIEWs">
    <Type Name="VIEW">
      <Column Name="TABLE_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="VIEW_DEFINITION" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CHECK_OPTION" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="IS_UPDATABLE" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="INFORMATION_SCHEMA.CHECK_CONSTRAINTS" Member="CHECK_CONSTRAINTs">
    <Type Name="CHECK_CONSTRAINT">
      <Column Name="CONSTRAINT_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CONSTRAINT_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CONSTRAINT_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="CHECK_CLAUSE" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="sys.columns" Member="column1s">
    <Type Name="column1">
      <Column Name="object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="column_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="system_type_id" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="user_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="max_length" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="precision" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="scale" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="collation_name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="is_nullable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_ansi_padded" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_rowguidcol" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_identity" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_computed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_filestream" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_replicated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_non_sql_subscribed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_merge_published" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_dts_replicated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_xml_document" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="xml_collection_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="default_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rule_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="is_sparse" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_column_set" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="sys.computed_columns" Member="computed_columns">
    <Type Name="computed_column">
      <Column Name="object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="column_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="system_type_id" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="user_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="max_length" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="precision" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="scale" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="collation_name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="is_nullable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_ansi_padded" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_rowguidcol" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_identity" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_filestream" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_replicated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_non_sql_subscribed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_merge_published" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_dts_replicated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_xml_document" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="xml_collection_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="default_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rule_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="definition" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="uses_database_collation" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_persisted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_computed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_sparse" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_column_set" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="sys.databases" Member="databases">
    <Type Name="database">
      <Column Name="name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="database_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="source_database_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="owner_sid" Type="System.Data.Linq.Binary" DbType="VarBinary(85)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="create_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="compatibility_level" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="collation_name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="user_access" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="user_access_desc" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="is_read_only" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_auto_close_on" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_auto_shrink_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="state" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="state_desc" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="is_in_standby" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_cleanly_shutdown" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_supplemental_logging_enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="snapshot_isolation_state" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="snapshot_isolation_state_desc" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="is_read_committed_snapshot_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="recovery_model" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="recovery_model_desc" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="page_verify_option" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="page_verify_option_desc" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="is_auto_create_stats_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_auto_update_stats_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_auto_update_stats_async_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_ansi_null_default_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_ansi_nulls_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_ansi_padding_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_ansi_warnings_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_arithabort_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_concat_null_yields_null_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_numeric_roundabort_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_quoted_identifier_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_recursive_triggers_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_cursor_close_on_commit_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_local_cursor_default" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_fulltext_enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_trustworthy_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_db_chaining_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_parameterization_forced" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_master_key_encrypted_by_server" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_subscribed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_merge_published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_distributor" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_sync_with_backup" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="service_broker_guid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="is_broker_enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="log_reuse_wait" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="log_reuse_wait_desc" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="is_date_correlation_on" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_cdc_enabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_encrypted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_honor_broker_priority_on" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="sys.foreign_key_columns" Member="foreign_key_columns">
    <Type Name="foreign_key_column">
      <Column Name="constraint_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="constraint_column_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="parent_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="parent_column_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="referenced_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="referenced_column_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="sys.foreign_keys" Member="foreign_keys">
    <Type Name="foreign_key">
      <Column Name="name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="principal_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="schema_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="parent_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="type_desc" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="create_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modify_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="is_ms_shipped" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_schema_published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="referenced_object_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="key_index_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="is_disabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_not_for_replication" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_not_trusted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="delete_referential_action" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="delete_referential_action_desc" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="update_referential_action" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="update_referential_action_desc" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="is_system_named" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="sys.function_order_columns" Member="function_order_columns">
    <Type Name="function_order_column">
      <Column Name="object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="order_column_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="column_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="is_descending" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="sys.identity_columns" Member="identity_columns">
    <Type Name="identity_column">
      <Column Name="object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="column_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="system_type_id" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="user_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="max_length" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="precision" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="scale" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="collation_name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="is_nullable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_ansi_padded" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_rowguidcol" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_identity" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_filestream" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_replicated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_non_sql_subscribed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_merge_published" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_dts_replicated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_xml_document" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="xml_collection_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="default_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rule_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="seed_value" Type="System.Object" DbType="Variant" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="increment_value" Type="System.Object" DbType="Variant" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="last_value" Type="System.Object" DbType="Variant" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="is_not_for_replication" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_computed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_sparse" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_column_set" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="sys.index_columns" Member="index_columns">
    <Type Name="index_column">
      <Column Name="object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="index_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="index_column_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="column_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="key_ordinal" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="partition_ordinal" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="is_descending_key" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_included_column" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="sys.indexes" Member="indexes">
    <Type Name="index">
      <Column Name="object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="index_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="type_desc" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="is_unique" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="data_space_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ignore_dup_key" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_primary_key" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_unique_constraint" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="fill_factor" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="is_padded" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_disabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_hypothetical" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="allow_row_locks" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="allow_page_locks" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="has_filter" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="filter_definition" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="sys.key_constraints" Member="key_constraints">
    <Type Name="key_constraint">
      <Column Name="name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="principal_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="schema_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="parent_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="type_desc" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="create_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modify_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="is_ms_shipped" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_schema_published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="unique_index_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="is_system_named" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="sys.linked_logins" Member="linked_logins">
    <Type Name="linked_login">
      <Column Name="server_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="local_principal_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="uses_self_credential" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="remote_name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="modify_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="sys.parameter_type_usages" Member="parameter_type_usages">
    <Type Name="parameter_type_usage">
      <Column Name="object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="parameter_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="sys.procedures" Member="procedures">
    <Type Name="procedure">
      <Column Name="name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="principal_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="schema_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="parent_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="type_desc" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="create_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modify_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="is_ms_shipped" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_schema_published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_auto_executed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_execution_replicated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_repl_serializable_only" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="skips_repl_constraints" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="sys.schemas" Member="schemas">
    <Type Name="schema">
      <Column Name="name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="schema_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="principal_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="sys.syscolumns" Member="syscolumns">
    <Type Name="syscolumn">
      <Column Name="name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="xtype" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="typestat" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="xusertype" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="length" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="xprec" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="xscale" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="colid" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="xoffset" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="bitpos" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="reserved" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="colstat" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="cdefault" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="domain" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="number" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="colorder" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="autoval" Type="System.Data.Linq.Binary" DbType="VarBinary(8000)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="offset" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="collationid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="language" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="usertype" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="printfmt" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="prec" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="scale" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="iscomputed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isoutparam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isnullable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="collation" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="tdscollation" Type="System.Data.Linq.Binary" DbType="Binary(5)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="sys.sysconstraints" Member="sysconstraints">
    <Type Name="sysconstraint">
      <Column Name="constid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="colid" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="spare1" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="actions" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="error" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="sys.sysdatabases" Member="sysdatabases">
    <Type Name="sysdatabase">
      <Column Name="name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="dbid" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="sid" Type="System.Data.Linq.Binary" DbType="VarBinary(85)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="mode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="crdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="reserved" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cmptlevel" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="filename" Type="System.String" DbType="NVarChar(260)" CanBeNull="true" />
      <Column Name="version" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="sys.sysforeignkeys" Member="sysforeignkeys">
    <Type Name="sysforeignkey">
      <Column Name="constid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fkeyid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rkeyid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fkey" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="rkey" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="keyno" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="sys.sysindexes" Member="sysindexes">
    <Type Name="sysindex">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="first" Type="System.Data.Linq.Binary" DbType="Binary(6)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="indid" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="root" Type="System.Data.Linq.Binary" DbType="Binary(6)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="minlen" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="keycnt" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="groupid" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="dpages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="reserved" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="used" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rowcnt" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="rowmodctr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="reserved3" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="reserved4" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="xmaxlen" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="maxirow" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="OrigFillFactor" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="StatVersion" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="reserved2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstIAM" Type="System.Data.Linq.Binary" DbType="Binary(6)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="impid" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="lockflags" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pgmodctr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="keys" Type="System.Data.Linq.Binary" DbType="VarBinary(1088)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="statblob" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="maxlen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rows" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="sys.sysobjects" Member="sysobjects">
    <Type Name="sysobject">
      <Column Name="name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="xtype" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="uid" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="info" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="base_schema_ver" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="replinfo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="parent_obj" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="crdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ftcatid" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="schema_ver" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="stats_schema_ver" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="userstat" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="sysstat" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="indexdel" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="refdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="deltrig" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="instrig" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="updtrig" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="seltrig" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cache" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="sys.system_objects" Member="system_objects">
    <Type Name="system_object">
      <Column Name="name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="principal_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="schema_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="parent_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="type_desc" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="create_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modify_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="is_ms_shipped" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_schema_published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="sys.systypes" Member="systypes">
    <Type Name="systype">
      <Column Name="name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="xtype" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="xusertype" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="length" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="xprec" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="xscale" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="tdefault" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="domain" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="uid" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="reserved" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="collationid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="usertype" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="variable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="allownulls" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="printfmt" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="prec" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="scale" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="collation" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="sys.table_types" Member="table_types">
    <Type Name="table_type">
      <Column Name="name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="system_type_id" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="user_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="schema_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="principal_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="max_length" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="precision" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="scale" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="collation_name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="is_nullable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_user_defined" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_assembly_type" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="default_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rule_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="is_table_type" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="type_table_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="sys.tables" Member="table1s">
    <Type Name="table1">
      <Column Name="name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="principal_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="schema_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="parent_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="type_desc" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="create_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modify_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="is_ms_shipped" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_schema_published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="lob_data_space_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="filestream_data_space_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="max_column_id_used" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lock_on_bulk_load" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="uses_ansi_nulls" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_replicated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="has_replication_filter" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_merge_published" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_sync_tran_subscribed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="has_unchecked_assembly_data" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="text_in_row_limit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="large_value_types_out_of_row" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_tracked_by_cdc" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="lock_escalation" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="lock_escalation_desc" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="sys.types" Member="types">
    <Type Name="type">
      <Column Name="name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="system_type_id" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="user_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="schema_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="principal_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="max_length" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="precision" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="scale" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="collation_name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="is_nullable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_user_defined" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_assembly_type" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="default_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rule_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="is_table_type" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="sys.views" Member="view1s">
    <Type Name="view1">
      <Column Name="name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="principal_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="schema_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="parent_object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="type_desc" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="create_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modify_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="is_ms_shipped" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_schema_published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_replicated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="has_replication_filter" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="has_opaque_metadata" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="has_unchecked_assembly_data" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="with_check_option" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_date_correlation_view" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_tracked_by_cdc" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE" Member="CONSTRAINT_COLUMN_USAGEs">
    <Type Name="CONSTRAINT_COLUMN_USAGE">
      <Column Name="TABLE_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="COLUMN_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CONSTRAINT_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CONSTRAINT_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CONSTRAINT_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS" Member="REFERENTIAL_CONSTRAINTs">
    <Type Name="REFERENTIAL_CONSTRAINT">
      <Column Name="CONSTRAINT_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CONSTRAINT_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CONSTRAINT_NAME" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="UNIQUE_CONSTRAINT_CATALOG" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="UNIQUE_CONSTRAINT_SCHEMA" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="UNIQUE_CONSTRAINT_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MATCH_OPTION" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="UPDATE_RULE" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="DELETE_RULE" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.uspLogError" Method="uspLogError">
    <Parameter Name="ErrorLogID" Parameter="errorLogID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ufnGetSalesOrderStatusText" Method="ufnGetSalesOrderStatusText" IsComposable="true">
    <Parameter Name="Status" Parameter="status" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.String" />
  </Function>
</Database>